/* Generated by            cobc 2.0.20140120 */
/* Generated from          animod.cbl */
/* Generated at            Nov 20 2014 13:38:55 */
/* GNU Cobol build date    Nov 20 2014 13:37:03 */
/* GNU Cobol package date  Jan 20 2014 07:40:53 UTC */
/* Compile command         ..\cobc -C animod.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"animod.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		20140120
#define  COB_MODULE_FORMATTED_DATE	"Nov 20 2014 13:38:55"
#define  COB_MODULE_DATE		20141120
#define  COB_MODULE_TIME		133855

/* Global variables */
#include "animod.c.h"

/* Function prototypes */

__declspec(dllexport) int			animod (cob_u8_t *);
static int		animod_ (const int, cob_u8_t *);

/* Functions */

/* PROGRAM-ID 'animod' */

/* ENTRY 'animod' */

int
animod (cob_u8_t *b_12)
{
  return animod_ (0, b_12);
}

static int
animod_ (const int entry, cob_u8_t *b_12)
{
  /* Program local variables */
  #include "animod.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;

  /* Initialize program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Save number of call params */
  module->module_num_params = cob_glob_ptr->cob_call_params;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 47        : Entry     animod                  : animod.cbl */
  l_2:;

  /* Line: 47        : Paragraph h00                     : animod.cbl */

  /* Line: 49        : MOVE               : animod.cbl */
  memset (b_12 + 1, 48, 2);

  /* Line: 50        : IF                 : animod.cbl */
  if (((int)(int)(*(b_12) - 79) == 0))
  {

    /* Line: 51        : MOVE               : animod.cbl */
    cob_move (COB_SET_DATA (f_15, b_12 + 3), &f_10);

    /* Line: 52        : OPEN               : animod.cbl */
    cob_open (h_ANIFILE, 2, 0, COB_SET_DATA (f_14, b_12 + 1));
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_num = 0;
      goto l_1;
      l_7:
      frame_ptr--;
    }

    /* Line: 53        : CLOSE              : animod.cbl */
    cob_close (h_ANIFILE, COB_SET_DATA (f_14, b_12 + 1), 0, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_num = 1;
      goto l_1;
      l_8:
      frame_ptr--;
    }

    /* Line: 54        : OPEN               : animod.cbl */
    cob_open (h_ANIFILE, 3, 0, COB_SET_DATA (f_14, b_12 + 1));
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_num = 2;
      goto l_1;
      l_9:
      frame_ptr--;
    }

    /* Line: 55        : GO TO              : animod.cbl */
    goto l_5;
  }

  /* Line: 57        : IF                 : animod.cbl */
  if (((int)(int)(*(b_12) - 67) == 0))
  {

    /* Line: 58        : CLOSE              : animod.cbl */
    cob_close (h_ANIFILE, COB_SET_DATA (f_14, b_12 + 1), 0, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_num = 3;
      goto l_1;
      l_10:
      frame_ptr--;
    }

    /* Line: 59        : GO TO              : animod.cbl */
    goto l_5;
  }

  /* Line: 61        : IF                 : animod.cbl */
  if (((int)(int)(*(b_12) - 82) == 0))
  {

    /* Line: 62        : MOVE               : animod.cbl */
    memmove (b_8, b_12 + 3, 74);

    /* Line: 63        : READ               : animod.cbl */
    cob_read (h_ANIFILE, &f_6, COB_SET_DATA (f_14, b_12 + 1), 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0506)
      {

        /* Line: 65        : MOVE               : animod.cbl */
        memcpy (b_12 + 1, "23", 2);

        /* Line: 66        : GO TO              : animod.cbl */
        goto l_6;
      }
      else
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_num = 4;
        goto l_1;
        l_11:
        frame_ptr--;
      }
    }

    /* Line: 68        : MOVE               : animod.cbl */
    memmove (b_12 + 3, b_8, 74);

    /* Line: 69        : GO TO              : animod.cbl */
    goto l_6;
  }

  /* Line: 71        : IF                 : animod.cbl */
  if (((int)(int)(*(b_12) - 87) == 0))
  {

    /* Line: 72        : MOVE               : animod.cbl */
    memmove (b_8, b_12 + 3, 74);

    /* Line: 73        : WRITE              : animod.cbl */
    cob_write (h_ANIFILE, &f_5, 0, COB_SET_DATA (f_14, b_12 + 1), 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_num = 5;
      goto l_1;
      l_12:
      frame_ptr--;
    }

    /* Line: 74        : GO TO              : animod.cbl */
    goto l_6;
  }

  /* Line: 76        : IF                 : animod.cbl */
  if (((int)(int)(*(b_12) - 85) == 0))
  {

    /* Line: 77        : MOVE               : animod.cbl */
    memmove (b_8, b_12 + 3, 74);

    /* Line: 78        : REWRITE            : animod.cbl */
    cob_rewrite (h_ANIFILE, &f_5, 0, COB_SET_DATA (f_14, b_12 + 1));
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_num = 6;
      goto l_1;
      l_13:
      frame_ptr--;
    }

    /* Line: 79        : GO TO              : animod.cbl */
    goto l_6;
  }

  /* Line: 81        : IF                 : animod.cbl */
  if (((int)(int)(*(b_12) - 78) == 0))
  {

    /* Line: 82        : READ               : animod.cbl */
    cob_read_next (h_ANIFILE, COB_SET_DATA (f_14, b_12 + 1), 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 83        : MOVE               : animod.cbl */
        memcpy (b_12 + 1, "10", 2);

        /* Line: 84        : GO TO              : animod.cbl */
        goto l_6;
      }
      else
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_num = 7;
        goto l_1;
        l_14:
        frame_ptr--;
      }
    }

    /* Line: 86        : MOVE               : animod.cbl */
    memmove (b_12 + 3, b_8, 74);

    /* Line: 87        : GO TO              : animod.cbl */
    goto l_6;
  }

  /* Line: 89        : IF                 : animod.cbl */
  if (((int)(int)(*(b_12) - 83) == 0))
  {

    /* Line: 90        : MOVE               : animod.cbl */
    memmove (b_8, b_12 + 3, 74);

    /* Line: 91        : START              : animod.cbl */
    cob_start (h_ANIFILE, 5, &f_6, NULL, COB_SET_DATA (f_14, b_12 + 1));
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0506)
      {

        /* Line: 93        : MOVE               : animod.cbl */
        memcpy (b_12 + 1, "23", 2);

        /* Line: 94        : GO TO              : animod.cbl */
        goto l_6;
      }
      else
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_num = 8;
        goto l_1;
        l_15:
        frame_ptr--;
      }
    }
  }

  /* Line: 96        : MOVE               : animod.cbl */
  memmove (b_12 + 3, b_8, 74);

  /* Line: 97        : GO TO              : animod.cbl */
  goto l_6;

  /* Line: 98        : Paragraph h90                     : animod.cbl */
  l_5:;

  /* Line: 99        : MOVE               : animod.cbl */
  memset (b_12 + 3, 32, 74);

  /* Line: 100       : Paragraph h99                     : animod.cbl */
  l_6:;

  /* Line: 102       : EXIT PROGRAM       : animod.cbl */
  if (module->next)
    goto exit_program;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;


  /* Paragraph Default Error Handler   */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_fatal_error (COB_FERROR_FILE);
  }

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto P_switch;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);


  /* Frame stack jump table */
  P_switch:
   switch (frame_ptr->return_address_num) {
   case 8:
     goto l_15;
   case 7:
     goto l_14;
   case 6:
     goto l_13;
   case 5:
     goto l_12;
   case 4:
     goto l_11;
   case 3:
     goto l_10;
   case 2:
     goto l_9;
   case 1:
     goto l_8;
   case 0:
     goto l_7;
   }
   cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  /* Initialize module structure */
  module->module_name = "animod";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())animod;
  module->module_cancel.funcptr = (void *(*)())animod_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 1;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  memset (b_9, 32, 256);
  memset (b_11, 32, 4096);


  if (!h_ANIFILE)
  {
    h_ANIFILE = cob_cache_malloc (sizeof(cob_file));
  }
  if (!k_ANIFILE)
  {
    k_ANIFILE = cob_cache_malloc (sizeof (cob_file_key) * 1);
  }
  k_ANIFILE->field = &f_6;
  k_ANIFILE->flag = 0;
  k_ANIFILE->offset = 0;
  h_ANIFILE->select_name = (const char *)"anifile";
  h_ANIFILE->file_status = h_ANIFILE_status;
  memset (h_ANIFILE_status, '0', 2);
  h_ANIFILE->assign = &f_10;
  h_ANIFILE->record = &f_8;
  h_ANIFILE->variable_record = NULL;
  h_ANIFILE->record_min = 74;
  h_ANIFILE->record_max = 74;
  h_ANIFILE->nkeys = 1;
  h_ANIFILE->keys = k_ANIFILE;
  h_ANIFILE->file = NULL;
  h_ANIFILE->fd = -1;
  h_ANIFILE->organization = 3;
  h_ANIFILE->access_mode = 2;
  h_ANIFILE->lock_mode = 0;
  h_ANIFILE->open_mode = 0;
  h_ANIFILE->flag_optional = 0;
  h_ANIFILE->last_open_mode = 0;
  h_ANIFILE->flag_operation = 0;
  h_ANIFILE->flag_nonexistent = 0;
  h_ANIFILE->flag_end_of_file = 0;
  h_ANIFILE->flag_begin_of_file = 0;
  h_ANIFILE->flag_first_read = 0;
  h_ANIFILE->flag_read_done = 0;
  h_ANIFILE->flag_select_features = 1;
  h_ANIFILE->flag_needs_nl = 0;
  h_ANIFILE->flag_needs_top = 0;
  h_ANIFILE->file_version = 1;

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  cob_close (h_ANIFILE, NULL, COB_CLOSE_NORMAL, 1);
  cob_cache_free (k_ANIFILE);
  k_ANIFILE = NULL;
  cob_cache_free (h_ANIFILE);
  h_ANIFILE = NULL;
  b_1 = 0;
  cob_cache_free (module);
  module = NULL;

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'animod' */

/* End functions */

